### ISSUE TITLE
Can u fix bug at last update wow

### ISSUE THREAD

**Issue by JohnnyOtkatilo** [dartraiden/PortGear#1]
The addon tries endlessly to put the gear back on, but to no avail because the error “does not fit in this slot” appears.

**Comment by dartraiden** [comment]
Seems like [EquipItemByName()](https://wowwiki-archive.fandom.com/wiki/API_EquipItemByName) is partially broken since 10.2.6

Now, if you specify not only the item id, but also the slot number, an error occurs.

Same issue:
https://github.com/Sluimerstand/EquipRecommendedGear/commit/111525726f8ef8d2b63b5a430ed9049f12eb2c52#diff-b125e62b8c0238cc3ad7b6cceb3705945116b050a8e3fe642cb479a32468e61aR566

**Comment by dartraiden** [comment]
Fixed in https://github.com/dartraiden/PortGear/commit/e5a5a1ea480d09b80c3ddd1eda8af31dcb4ad436
